### ISSUE TITLE
[SSR Public Catalog] Update search and filtering to use SSR

### ISSUE THREAD

**Issue by zstix** [newrelic/instant-observability-website#42]
## Description
Once we have established a pattern for querying NerdGraph for quickstarts on the landing page (#1853), we should use the API to power the functionality for searching and filtering the results. This would _replace_ our client-side functionality (which has gotten to be pretty complicated).

#### GraphQL
Here's an example query:

```graphql
{
  actor {
    nr1Catalog {
      search(filter: {components: ALERTS}) {
        results {
          ... on Nr1CatalogQuickstart {
            id
            metadata {
              displayName
            }
          }
        }
      }
    }
  }
}
```

### Note
A large portion of this work as already been completed in [this](https://github.com/newrelic/developer-website/pull/1949/files) pull request. It should be pulled over to the new site.

## Acceptance Criteria
* [x] https://github.com/newrelic/developer-website/issues/1821 (proof-of-concept & Gatsby upgrade)
* [x] https://github.com/newrelic/developer-website/issues/1852 (feature branch & Gatsby Cloud)
* [x] https://github.com/newrelic/developer-website/issues/1853 (landing page via SSR)
* [x] Update search to use use SSR + a NerdGraph API call
* [x] Update filtering to use SSR + a NerdGraph API call
* [ ] Add tests for search
* [ ] Add tests for filter
* [x] Ensure that searching and filtering still updates the URL as it did previously
* [x] Remove all unused client-side search and filter code

**Comment by aswanson-nr** [comment]
Did not add additional unit tests, because these changes abstract all business logic out to the catalog service.
