### ISSUE TITLE
[SSR Public Catalog] Remove code / automation for manually fetching quickstarts

### ISSUE THREAD

**Issue by zstix** [newrelic/instant-observability-website#43]
## Description
Once we have fully swapped [the landing page](https://github.com/newrelic/developer-website/issues/1853) and [the detail page](https://github.com/newrelic/developer-website/issues/1854) over to being powered by Gatsby SSR functions, we no longer need to have a Github workflow that runs every few hours to make API requests and build up a JSON file.

This ticket is to clean up that functionality and the files we are no longer using.

## Acceptance Criteria
* [x] https://github.com/newrelic/developer-website/issues/1853 (landing page via SSR)
* [ ] newrelic/instant-observability-website#42 (search and filter via SSR)
* [x] https://github.com/newrelic/developer-website/issues/1854 (details page via SSR)
* [x] Remove the [Github workflow](https://github.com/newrelic/developer-website/blob/develop/.github/workflows/fetch-quickstarts.yml)
* [x] Remove the [fetch quickstarts script](https://github.com/newrelic/developer-website/blob/develop/scripts/actions/fetch-quickstarts.js) (and related tests)
* [x] Remove the [quickstarts JSON file](https://github.com/newrelic/developer-website/blob/main/src/data/quickstarts.json)
* [x] Remove any code that references the quickstart JSON file ([example](https://github.com/newrelic/developer-website/blob/develop/scripts/list-quickstart-urls.js))
* [ ] Edit the way we give related resources the quickstart slugs (we'll need to make an api call since we don't have quickstarts in the gatsby schema anymore)
* [ ] Remove any Github secrets we no longer need
