### ISSUE TITLE
[SSR Public Catalog] Instrumentation & Alerting for API calls to NerdGraph

### ISSUE THREAD

**Issue by zstix** [newrelic/instant-observability-website#45]
## Description
As part of "production readiness" for swapping New Relic I/O over to being powered by NerdGraph, we should instrument the API calls being made and set up some alerting for failures.

It's not clear in which context the API calls are being made: are they happening in the browser or are Gatsby's Cloud Functions executing "server-side" somewhere? If they're happening client-side, we may be able to use New Relic's Browser agent to log these events. If they're happening server-side, then we may need to leverage [New Relic custom events](newrelic/instant-observability-website#42) (since we don't have an agent installed in Gatsby).

## Acceptance Criteria
* [x] https://github.com/newrelic/developer-website/issues/1821 (proof-of-concept & Gatsby upgrade)
* [x] https://github.com/newrelic/developer-website/issues/1852 (feature branch & Gatsby Cloud)
* [x] https://github.com/newrelic/developer-website/issues/1853 (landing page via SSR)
* [x] newrelic/instant-observability-website#42 (search and filter via SSR)
* [x] https://github.com/newrelic/developer-website/issues/1854 (details page via SSR)
* [x] Determine how we can get API call information into New Relic
* [x] Set up instrumentation for API calls to NerdGraph for `/instant-observability`
* [x] Set up instrumentation for API calls to NerdGraph for the quickstart detail page
* [x] Set up an alert condition for any failed API calls to the service
  * [x] alert on production instead of our feature branch 
* [x] Charts that track successes and failures of API calls to  [troubleshooting dashboard](https://staging.onenr.io/0JBQr66VbQZ)
  * [x] track production instead of our feature branch
* [x] update wiki with new events tracked, links to dashboard, alerts, etc

**Comment by nr-kkenney** [comment]
here is the dashboard page i created: https://staging.onenr.io/0z7wkkBWlwL

it currently displays:
- success, failure count
- success %
- 10 most recent error messages, urls
